/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as PassageiroRouteImport } from './routes/passageiro'
import { Route as PilotoRouteImport } from './routes/piloto'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DesignSystemComponentesRouteImport } from './routes/design-system/componentes'
import { Route as PassageiroIndexRouteImport } from './routes/passageiro/index'
import { Route as PassageiroBoasVindasRouteImport } from './routes/passageiro/boas-vindas'
import { Route as PassageiroBuscandoRouteImport } from './routes/passageiro/buscando'
import { Route as PassageiroCadastroRouteImport } from './routes/passageiro/cadastro'
import { Route as PassageiroConfirmarCorridaRouteImport } from './routes/passageiro/confirmar-corrida'
import { Route as PassageiroCorridasRouteImport } from './routes/passageiro/corridas'
import { Route as PassageiroDestinoRouteImport } from './routes/passageiro/destino'
import { Route as PassageiroEntrarRouteImport } from './routes/passageiro/entrar'
import { Route as PassageiroInicioRouteImport } from './routes/passageiro/inicio'
import { Route as PassageiroLocaisSalvosRouteImport } from './routes/passageiro/locais-salvos'
import { Route as PassageiroLocalizarRouteImport } from './routes/passageiro/localizar'
import { Route as PassageiroNotificacoesRouteImport } from './routes/passageiro/notificacoes'
import { Route as PassageiroPerfilRouteImport } from './routes/passageiro/perfil'
import { Route as PassageiroPermissoesRouteImport } from './routes/passageiro/permissoes'
import { Route as PassageiroSegurancaRouteImport } from './routes/passageiro/seguranca'
import { Route as PassageiroVerificacaoRouteImport } from './routes/passageiro/verificacao'
import { Route as PilotoIndexRouteImport } from './routes/piloto/index'
import { Route as SimuladorIndexRouteImport } from './routes/simulador/index'
import { Route as PassageiroCancelarRideIdRouteImport } from './routes/passageiro/cancelar.$rideId'
import { Route as PassageiroChatRideIdRouteImport } from './routes/passageiro/chat/$rideId'
import { Route as PassageiroCorridaRideIdRouteImport } from './routes/passageiro/corrida.$rideId'
import { Route as PassageiroCorridaRideIdConcluidaRouteImport } from './routes/passageiro/corrida.$rideId.concluida'
import { Route as PassageiroCorridaRideIdEmAndamentoRouteImport } from './routes/passageiro/corrida/$rideId/em-andamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroRoute = PassageiroRouteImport.update({
  id: '/passageiro',
  path: '/passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotoRoute = PilotoRouteImport.update({
  id: '/piloto',
  path: '/piloto',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DesignSystemComponentesRoute = DesignSystemComponentesRouteImport.update({
  id: '/componentes',
  path: '/componentes',
  getParentRoute: () => DesignSystemRoute,
} as any)
const PassageiroIndexRoute = PassageiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroBoasVindasRoute = PassageiroBoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroBuscandoRoute = PassageiroBuscandoRouteImport.update({
  id: '/buscando',
  path: '/buscando',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroCadastroRoute = PassageiroCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroConfirmarCorridaRoute =
  PassageiroConfirmarCorridaRouteImport.update({
    id: '/confirmar-corrida',
    path: '/confirmar-corrida',
    getParentRoute: () => PassageiroRoute,
  } as any)
const PassageiroCorridasRoute = PassageiroCorridasRouteImport.update({
  id: '/corridas',
  path: '/corridas',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroDestinoRoute = PassageiroDestinoRouteImport.update({
  id: '/destino',
  path: '/destino',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroEntrarRoute = PassageiroEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroInicioRoute = PassageiroInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroLocaisSalvosRoute = PassageiroLocaisSalvosRouteImport.update({
  id: '/locais-salvos',
  path: '/locais-salvos',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroLocalizarRoute = PassageiroLocalizarRouteImport.update({
  id: '/localizar',
  path: '/localizar',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroNotificacoesRoute = PassageiroNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroPerfilRoute = PassageiroPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroPermissoesRoute = PassageiroPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroSegurancaRoute = PassageiroSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroVerificacaoRoute = PassageiroVerificacaoRouteImport.update({
  id: '/verificacao',
  path: '/verificacao',
  getParentRoute: () => PassageiroRoute,
} as any)
const PilotoIndexRoute = PilotoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PilotoRoute,
} as any)
const SimuladorIndexRoute = SimuladorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SimuladorRoute,
} as any)
const PassageiroCancelarRideIdRoute =
  PassageiroCancelarRideIdRouteImport.update({
    id: '/cancelar/$rideId',
    path: '/cancelar/$rideId',
    getParentRoute: () => PassageiroRoute,
  } as any)
const PassageiroChatRideIdRoute = PassageiroChatRideIdRouteImport.update({
  id: '/chat/$rideId',
  path: '/chat/$rideId',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroCorridaRideIdRoute = PassageiroCorridaRideIdRouteImport.update({
  id: '/corrida/$rideId',
  path: '/corrida/$rideId',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroCorridaRideIdConcluidaRoute =
  PassageiroCorridaRideIdConcluidaRouteImport.update({
    id: '/concluida',
    path: '/concluida',
    getParentRoute: () => PassageiroCorridaRideIdRoute,
  } as any)
const PassageiroCorridaRideIdEmAndamentoRoute =
  PassageiroCorridaRideIdEmAndamentoRouteImport.update({
    id: '/em-andamento',
    path: '/em-andamento',
    getParentRoute: () => PassageiroCorridaRideIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/design-system': typeof DesignSystemRouteWithChildren
  '/passageiro': typeof PassageiroRouteWithChildren
  '/piloto': typeof PilotoRouteWithChildren
  '/simulador': typeof SimuladorRouteWithChildren
  '/design-system/componentes': typeof DesignSystemComponentesRoute
  '/passageiro/boas-vindas': typeof PassageiroBoasVindasRoute
  '/passageiro/buscando': typeof PassageiroBuscandoRoute
  '/passageiro/cadastro': typeof PassageiroCadastroRoute
  '/passageiro/confirmar-corrida': typeof PassageiroConfirmarCorridaRoute
  '/passageiro/corridas': typeof PassageiroCorridasRoute
  '/passageiro/destino': typeof PassageiroDestinoRoute
  '/passageiro/entrar': typeof PassageiroEntrarRoute
  '/passageiro/inicio': typeof PassageiroInicioRoute
  '/passageiro/locais-salvos': typeof PassageiroLocaisSalvosRoute
  '/passageiro/localizar': typeof PassageiroLocalizarRoute
  '/passageiro/notificacoes': typeof PassageiroNotificacoesRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/passageiro/permissoes': typeof PassageiroPermissoesRoute
  '/passageiro/seguranca': typeof PassageiroSegurancaRoute
  '/passageiro/verificacao': typeof PassageiroVerificacaoRoute
  '/admin/': typeof AdminIndexRoute
  '/passageiro/': typeof PassageiroIndexRoute
  '/piloto/': typeof PilotoIndexRoute
  '/simulador/': typeof SimuladorIndexRoute
  '/passageiro/cancelar/$rideId': typeof PassageiroCancelarRideIdRoute
  '/passageiro/chat/$rideId': typeof PassageiroChatRideIdRoute
  '/passageiro/corrida/$rideId': typeof PassageiroCorridaRideIdRouteWithChildren
  '/passageiro/corrida/$rideId/concluida': typeof PassageiroCorridaRideIdConcluidaRoute
  '/passageiro/corrida/$rideId/em-andamento': typeof PassageiroCorridaRideIdEmAndamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRouteWithChildren
  '/design-system/componentes': typeof DesignSystemComponentesRoute
  '/passageiro/boas-vindas': typeof PassageiroBoasVindasRoute
  '/passageiro/buscando': typeof PassageiroBuscandoRoute
  '/passageiro/cadastro': typeof PassageiroCadastroRoute
  '/passageiro/confirmar-corrida': typeof PassageiroConfirmarCorridaRoute
  '/passageiro/corridas': typeof PassageiroCorridasRoute
  '/passageiro/destino': typeof PassageiroDestinoRoute
  '/passageiro/entrar': typeof PassageiroEntrarRoute
  '/passageiro/inicio': typeof PassageiroInicioRoute
  '/passageiro/locais-salvos': typeof PassageiroLocaisSalvosRoute
  '/passageiro/localizar': typeof PassageiroLocalizarRoute
  '/passageiro/notificacoes': typeof PassageiroNotificacoesRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/passageiro/permissoes': typeof PassageiroPermissoesRoute
  '/passageiro/seguranca': typeof PassageiroSegurancaRoute
  '/passageiro/verificacao': typeof PassageiroVerificacaoRoute
  '/admin': typeof AdminIndexRoute
  '/passageiro': typeof PassageiroIndexRoute
  '/piloto': typeof PilotoIndexRoute
  '/simulador': typeof SimuladorIndexRoute
  '/passageiro/cancelar/$rideId': typeof PassageiroCancelarRideIdRoute
  '/passageiro/chat/$rideId': typeof PassageiroChatRideIdRoute
  '/passageiro/corrida/$rideId': typeof PassageiroCorridaRideIdRouteWithChildren
  '/passageiro/corrida/$rideId/concluida': typeof PassageiroCorridaRideIdConcluidaRoute
  '/passageiro/corrida/$rideId/em-andamento': typeof PassageiroCorridaRideIdEmAndamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/design-system': typeof DesignSystemRouteWithChildren
  '/passageiro': typeof PassageiroRouteWithChildren
  '/piloto': typeof PilotoRouteWithChildren
  '/simulador': typeof SimuladorRouteWithChildren
  '/design-system/componentes': typeof DesignSystemComponentesRoute
  '/passageiro/boas-vindas': typeof PassageiroBoasVindasRoute
  '/passageiro/buscando': typeof PassageiroBuscandoRoute
  '/passageiro/cadastro': typeof PassageiroCadastroRoute
  '/passageiro/confirmar-corrida': typeof PassageiroConfirmarCorridaRoute
  '/passageiro/corridas': typeof PassageiroCorridasRoute
  '/passageiro/destino': typeof PassageiroDestinoRoute
  '/passageiro/entrar': typeof PassageiroEntrarRoute
  '/passageiro/inicio': typeof PassageiroInicioRoute
  '/passageiro/locais-salvos': typeof PassageiroLocaisSalvosRoute
  '/passageiro/localizar': typeof PassageiroLocalizarRoute
  '/passageiro/notificacoes': typeof PassageiroNotificacoesRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/passageiro/permissoes': typeof PassageiroPermissoesRoute
  '/passageiro/seguranca': typeof PassageiroSegurancaRoute
  '/passageiro/verificacao': typeof PassageiroVerificacaoRoute
  '/admin/': typeof AdminIndexRoute
  '/passageiro/': typeof PassageiroIndexRoute
  '/piloto/': typeof PilotoIndexRoute
  '/simulador/': typeof SimuladorIndexRoute
  '/passageiro/cancelar/$rideId': typeof PassageiroCancelarRideIdRoute
  '/passageiro/chat/$rideId': typeof PassageiroChatRideIdRoute
  '/passageiro/corrida/$rideId': typeof PassageiroCorridaRideIdRouteWithChildren
  '/passageiro/corrida/$rideId/concluida': typeof PassageiroCorridaRideIdConcluidaRoute
  '/passageiro/corrida/$rideId/em-andamento': typeof PassageiroCorridaRideIdEmAndamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/design-system'
    | '/passageiro'
    | '/piloto'
    | '/simulador'
    | '/design-system/componentes'
    | '/passageiro/boas-vindas'
    | '/passageiro/buscando'
    | '/passageiro/cadastro'
    | '/passageiro/confirmar-corrida'
    | '/passageiro/corridas'
    | '/passageiro/destino'
    | '/passageiro/entrar'
    | '/passageiro/inicio'
    | '/passageiro/locais-salvos'
    | '/passageiro/localizar'
    | '/passageiro/notificacoes'
    | '/passageiro/perfil'
    | '/passageiro/permissoes'
    | '/passageiro/seguranca'
    | '/passageiro/verificacao'
    | '/admin/'
    | '/passageiro/'
    | '/piloto/'
    | '/simulador/'
    | '/passageiro/cancelar/$rideId'
    | '/passageiro/chat/$rideId'
    | '/passageiro/corrida/$rideId'
    | '/passageiro/corrida/$rideId/concluida'
    | '/passageiro/corrida/$rideId/em-andamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/design-system/componentes'
    | '/passageiro/boas-vindas'
    | '/passageiro/buscando'
    | '/passageiro/cadastro'
    | '/passageiro/confirmar-corrida'
    | '/passageiro/corridas'
    | '/passageiro/destino'
    | '/passageiro/entrar'
    | '/passageiro/inicio'
    | '/passageiro/locais-salvos'
    | '/passageiro/localizar'
    | '/passageiro/notificacoes'
    | '/passageiro/perfil'
    | '/passageiro/permissoes'
    | '/passageiro/seguranca'
    | '/passageiro/verificacao'
    | '/admin'
    | '/passageiro'
    | '/piloto'
    | '/simulador'
    | '/passageiro/cancelar/$rideId'
    | '/passageiro/chat/$rideId'
    | '/passageiro/corrida/$rideId'
    | '/passageiro/corrida/$rideId/concluida'
    | '/passageiro/corrida/$rideId/em-andamento'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/design-system'
    | '/passageiro'
    | '/piloto'
    | '/simulador'
    | '/design-system/componentes'
    | '/passageiro/boas-vindas'
    | '/passageiro/buscando'
    | '/passageiro/cadastro'
    | '/passageiro/confirmar-corrida'
    | '/passageiro/corridas'
    | '/passageiro/destino'
    | '/passageiro/entrar'
    | '/passageiro/inicio'
    | '/passageiro/locais-salvos'
    | '/passageiro/localizar'
    | '/passageiro/notificacoes'
    | '/passageiro/perfil'
    | '/passageiro/permissoes'
    | '/passageiro/seguranca'
    | '/passageiro/verificacao'
    | '/admin/'
    | '/passageiro/'
    | '/piloto/'
    | '/simulador/'
    | '/passageiro/cancelar/$rideId'
    | '/passageiro/chat/$rideId'
    | '/passageiro/corrida/$rideId'
    | '/passageiro/corrida/$rideId/concluida'
    | '/passageiro/corrida/$rideId/em-andamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRouteWithChildren
  PassageiroRoute: typeof PassageiroRouteWithChildren
  PilotoRoute: typeof PilotoRouteWithChildren
  SimuladorRoute: typeof SimuladorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro': {
      id: '/passageiro'
      path: '/passageiro'
      fullPath: '/passageiro'
      preLoaderRoute: typeof PassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piloto': {
      id: '/piloto'
      path: '/piloto'
      fullPath: '/piloto'
      preLoaderRoute: typeof PilotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/design-system/componentes': {
      id: '/design-system/componentes'
      path: '/componentes'
      fullPath: '/design-system/componentes'
      preLoaderRoute: typeof DesignSystemComponentesRouteImport
      parentRoute: typeof DesignSystemRoute
    }
    '/passageiro/': {
      id: '/passageiro/'
      path: '/'
      fullPath: '/passageiro/'
      preLoaderRoute: typeof PassageiroIndexRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/boas-vindas': {
      id: '/passageiro/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/passageiro/boas-vindas'
      preLoaderRoute: typeof PassageiroBoasVindasRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/buscando': {
      id: '/passageiro/buscando'
      path: '/buscando'
      fullPath: '/passageiro/buscando'
      preLoaderRoute: typeof PassageiroBuscandoRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/cadastro': {
      id: '/passageiro/cadastro'
      path: '/cadastro'
      fullPath: '/passageiro/cadastro'
      preLoaderRoute: typeof PassageiroCadastroRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/confirmar-corrida': {
      id: '/passageiro/confirmar-corrida'
      path: '/confirmar-corrida'
      fullPath: '/passageiro/confirmar-corrida'
      preLoaderRoute: typeof PassageiroConfirmarCorridaRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/corridas': {
      id: '/passageiro/corridas'
      path: '/corridas'
      fullPath: '/passageiro/corridas'
      preLoaderRoute: typeof PassageiroCorridasRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/destino': {
      id: '/passageiro/destino'
      path: '/destino'
      fullPath: '/passageiro/destino'
      preLoaderRoute: typeof PassageiroDestinoRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/entrar': {
      id: '/passageiro/entrar'
      path: '/entrar'
      fullPath: '/passageiro/entrar'
      preLoaderRoute: typeof PassageiroEntrarRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/inicio': {
      id: '/passageiro/inicio'
      path: '/inicio'
      fullPath: '/passageiro/inicio'
      preLoaderRoute: typeof PassageiroInicioRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/locais-salvos': {
      id: '/passageiro/locais-salvos'
      path: '/locais-salvos'
      fullPath: '/passageiro/locais-salvos'
      preLoaderRoute: typeof PassageiroLocaisSalvosRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/localizar': {
      id: '/passageiro/localizar'
      path: '/localizar'
      fullPath: '/passageiro/localizar'
      preLoaderRoute: typeof PassageiroLocalizarRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/notificacoes': {
      id: '/passageiro/notificacoes'
      path: '/notificacoes'
      fullPath: '/passageiro/notificacoes'
      preLoaderRoute: typeof PassageiroNotificacoesRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/perfil': {
      id: '/passageiro/perfil'
      path: '/perfil'
      fullPath: '/passageiro/perfil'
      preLoaderRoute: typeof PassageiroPerfilRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/permissoes': {
      id: '/passageiro/permissoes'
      path: '/permissoes'
      fullPath: '/passageiro/permissoes'
      preLoaderRoute: typeof PassageiroPermissoesRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/seguranca': {
      id: '/passageiro/seguranca'
      path: '/seguranca'
      fullPath: '/passageiro/seguranca'
      preLoaderRoute: typeof PassageiroSegurancaRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/verificacao': {
      id: '/passageiro/verificacao'
      path: '/verificacao'
      fullPath: '/passageiro/verificacao'
      preLoaderRoute: typeof PassageiroVerificacaoRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/piloto/': {
      id: '/piloto/'
      path: '/'
      fullPath: '/piloto/'
      preLoaderRoute: typeof PilotoIndexRouteImport
      parentRoute: typeof PilotoRoute
    }
    '/simulador/': {
      id: '/simulador/'
      path: '/'
      fullPath: '/simulador/'
      preLoaderRoute: typeof SimuladorIndexRouteImport
      parentRoute: typeof SimuladorRoute
    }
    '/passageiro/cancelar/$rideId': {
      id: '/passageiro/cancelar/$rideId'
      path: '/cancelar/$rideId'
      fullPath: '/passageiro/cancelar/$rideId'
      preLoaderRoute: typeof PassageiroCancelarRideIdRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/chat/$rideId': {
      id: '/passageiro/chat/$rideId'
      path: '/chat/$rideId'
      fullPath: '/passageiro/chat/$rideId'
      preLoaderRoute: typeof PassageiroChatRideIdRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/corrida/$rideId': {
      id: '/passageiro/corrida/$rideId'
      path: '/corrida/$rideId'
      fullPath: '/passageiro/corrida/$rideId'
      preLoaderRoute: typeof PassageiroCorridaRideIdRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/corrida/$rideId/concluida': {
      id: '/passageiro/corrida/$rideId/concluida'
      path: '/concluida'
      fullPath: '/passageiro/corrida/$rideId/concluida'
      preLoaderRoute: typeof PassageiroCorridaRideIdConcluidaRouteImport
      parentRoute: typeof PassageiroCorridaRideIdRoute
    }
    '/passageiro/corrida/$rideId/em-andamento': {
      id: '/passageiro/corrida/$rideId/em-andamento'
      path: '/em-andamento'
      fullPath: '/passageiro/corrida/$rideId/em-andamento'
      preLoaderRoute: typeof PassageiroCorridaRideIdEmAndamentoRouteImport
      parentRoute: typeof PassageiroCorridaRideIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DesignSystemRouteChildren {
  DesignSystemComponentesRoute: typeof DesignSystemComponentesRoute
}

const DesignSystemRouteChildren: DesignSystemRouteChildren = {
  DesignSystemComponentesRoute: DesignSystemComponentesRoute,
}

const DesignSystemRouteWithChildren = DesignSystemRoute._addFileChildren(
  DesignSystemRouteChildren,
)

interface PassageiroCorridaRideIdRouteChildren {
  PassageiroCorridaRideIdConcluidaRoute: typeof PassageiroCorridaRideIdConcluidaRoute
  PassageiroCorridaRideIdEmAndamentoRoute: typeof PassageiroCorridaRideIdEmAndamentoRoute
}

const PassageiroCorridaRideIdRouteChildren: PassageiroCorridaRideIdRouteChildren =
  {
    PassageiroCorridaRideIdConcluidaRoute:
      PassageiroCorridaRideIdConcluidaRoute,
    PassageiroCorridaRideIdEmAndamentoRoute:
      PassageiroCorridaRideIdEmAndamentoRoute,
  }

const PassageiroCorridaRideIdRouteWithChildren =
  PassageiroCorridaRideIdRoute._addFileChildren(
    PassageiroCorridaRideIdRouteChildren,
  )

interface PassageiroRouteChildren {
  PassageiroBoasVindasRoute: typeof PassageiroBoasVindasRoute
  PassageiroBuscandoRoute: typeof PassageiroBuscandoRoute
  PassageiroCadastroRoute: typeof PassageiroCadastroRoute
  PassageiroConfirmarCorridaRoute: typeof PassageiroConfirmarCorridaRoute
  PassageiroCorridasRoute: typeof PassageiroCorridasRoute
  PassageiroDestinoRoute: typeof PassageiroDestinoRoute
  PassageiroEntrarRoute: typeof PassageiroEntrarRoute
  PassageiroInicioRoute: typeof PassageiroInicioRoute
  PassageiroLocaisSalvosRoute: typeof PassageiroLocaisSalvosRoute
  PassageiroLocalizarRoute: typeof PassageiroLocalizarRoute
  PassageiroNotificacoesRoute: typeof PassageiroNotificacoesRoute
  PassageiroPerfilRoute: typeof PassageiroPerfilRoute
  PassageiroPermissoesRoute: typeof PassageiroPermissoesRoute
  PassageiroSegurancaRoute: typeof PassageiroSegurancaRoute
  PassageiroVerificacaoRoute: typeof PassageiroVerificacaoRoute
  PassageiroIndexRoute: typeof PassageiroIndexRoute
  PassageiroCancelarRideIdRoute: typeof PassageiroCancelarRideIdRoute
  PassageiroChatRideIdRoute: typeof PassageiroChatRideIdRoute
  PassageiroCorridaRideIdRoute: typeof PassageiroCorridaRideIdRouteWithChildren
}

const PassageiroRouteChildren: PassageiroRouteChildren = {
  PassageiroBoasVindasRoute: PassageiroBoasVindasRoute,
  PassageiroBuscandoRoute: PassageiroBuscandoRoute,
  PassageiroCadastroRoute: PassageiroCadastroRoute,
  PassageiroConfirmarCorridaRoute: PassageiroConfirmarCorridaRoute,
  PassageiroCorridasRoute: PassageiroCorridasRoute,
  PassageiroDestinoRoute: PassageiroDestinoRoute,
  PassageiroEntrarRoute: PassageiroEntrarRoute,
  PassageiroInicioRoute: PassageiroInicioRoute,
  PassageiroLocaisSalvosRoute: PassageiroLocaisSalvosRoute,
  PassageiroLocalizarRoute: PassageiroLocalizarRoute,
  PassageiroNotificacoesRoute: PassageiroNotificacoesRoute,
  PassageiroPerfilRoute: PassageiroPerfilRoute,
  PassageiroPermissoesRoute: PassageiroPermissoesRoute,
  PassageiroSegurancaRoute: PassageiroSegurancaRoute,
  PassageiroVerificacaoRoute: PassageiroVerificacaoRoute,
  PassageiroIndexRoute: PassageiroIndexRoute,
  PassageiroCancelarRideIdRoute: PassageiroCancelarRideIdRoute,
  PassageiroChatRideIdRoute: PassageiroChatRideIdRoute,
  PassageiroCorridaRideIdRoute: PassageiroCorridaRideIdRouteWithChildren,
}

const PassageiroRouteWithChildren = PassageiroRoute._addFileChildren(
  PassageiroRouteChildren,
)

interface PilotoRouteChildren {
  PilotoIndexRoute: typeof PilotoIndexRoute
}

const PilotoRouteChildren: PilotoRouteChildren = {
  PilotoIndexRoute: PilotoIndexRoute,
}

const PilotoRouteWithChildren =
  PilotoRoute._addFileChildren(PilotoRouteChildren)

interface SimuladorRouteChildren {
  SimuladorIndexRoute: typeof SimuladorIndexRoute
}

const SimuladorRouteChildren: SimuladorRouteChildren = {
  SimuladorIndexRoute: SimuladorIndexRoute,
}

const SimuladorRouteWithChildren = SimuladorRoute._addFileChildren(
  SimuladorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DesignSystemRoute: DesignSystemRouteWithChildren,
  PassageiroRoute: PassageiroRouteWithChildren,
  PilotoRoute: PilotoRouteWithChildren,
  SimuladorRoute: SimuladorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
